version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: resume-matcher-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - resume-matcher-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    container_name: resume-matcher-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OLLAMA_URL=http://ollama:11434
      - DATABASE_URL=sqlite:///app/data/app.db
    volumes:
      - backend_data:/app/data
      - ./apps/backend/app.db:/app/app.db:rw
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - resume-matcher-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    container_name: resume-matcher-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - resume-matcher-network

volumes:
  ollama_data:
    driver: local
  backend_data:
    driver: local

networks:
  resume-matcher-network:
    driver: bridge 