version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: resume-matcher-ollama-dev
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data_dev:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - resume-matcher-network-dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    container_name: resume-matcher-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OLLAMA_URL=http://ollama:11434
      - DATABASE_URL=sqlite:///app/data/app.db
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./apps/backend:/app:rw
      - backend_data_dev:/app/data
      - /app/.venv
      - /app/__pycache__
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - resume-matcher-network-dev
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    container_name: resume-matcher-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8000
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    volumes:
      - ./apps/frontend:/app:rw
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - resume-matcher-network-dev
    command: ["npm", "run", "dev"]

volumes:
  ollama_data_dev:
    driver: local
  backend_data_dev:
    driver: local

networks:
  resume-matcher-network-dev:
    driver: bridge 